server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.222.230:3306/kksql?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 10 # 最大连接池
      max-lifetime: 1770000
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.wangcr.kk.web.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰命名匹配
  configuration:
    map-underscore-to-camel-case: true
